### ISSUE TITLE
Error creating a new chat thread

### ISSUE THREAD

**Issue by manvirdevs** [Azure-Samples/communication-services-contoso-med-app#9]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 1. Deploy all pre-requisites/components/solutions to Azure
>     1. **build** version of the _contoso-web-app_
>     2. **full code** of _contso-node-api_
> 2. Login as Doctor and Patient on separate browsers to _contoso-web-app_
> 3. Create a booking with a Doctor, and start Chat

### Any log messages given by the failure
Following log messages are seen for the **contoso-node-api** solution:
> creating new thread...
> initializing chat client...
> TypeError: CommunicationUserCredential is not a constructor
>     at Object.createThread (C:\home\site\wwwroot\services\chat.service.js:62:50)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async createThread (C:\home\site\wwwroot\controllers\chat.controller.js:8:20)
> POST /chat/createThread 200 205.443 ms - -

### Expected/desired behavior
>A new chat thread should be created and message should be delivered to the other party.

### OS and Version?
> Windows 7, 8 or 10. 

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by manvirdevs** [comment]
Dupliate of [this issue](https://github.com/Azure-Samples/communication-services-contoso-med-app/issues/5#issue-835596524); closing for now.
